#!/bin/sh
rm -r output
rm -r /tmp/lapel
meson --prefix=/tmp/lapel . output
meson compile -C output
meson install -C output
GSETTINGS_SCHEMA_DIR=/tmp/lapel/share/glib-2.0/schemas GTK_DEBUG=interactive /tmp/lapel/bin/lapel
