#!/bin/sh
if [ ! -e src ]; then echo "Not in aspinwall source directory"; exit 1; fi
if [ -e output ]; then rm -r output; fi
if [ -e /tmp/aspinwall ]; then rm -r /tmp/aspinwall; fi
meson --prefix=/tmp/aspinwall . output
meson compile -C output
meson compile lapel-update-po -C output
